// Run with playwright-cli run-code against tests/fixtures/web-ui-host.ts.
async (page) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('button', { name: 'A new home for Shepherd', exact: true }).click();
  await page.getByText('Connected', { exact: true }).waitFor();
  await page.getByText('Where did we leave off?', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Message Shepherd' }).fill('Please request approval');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('button', { name: 'Allow once', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Allow once', exact: true }).click();
  await page.getByRole('region', { name: 'Pending approvals' }).waitFor({ state: 'detached' });
  await page.getByText('Connected', { exact: true }).waitFor();
  const replies = await page.getByText('Let’s make it happen.', { exact: true }).count();
  if (replies !== 1) throw new Error(`Expected one canonical response, found ${replies}`);
  await page.route('**/messages', route => route.abort());
  await page.getByRole('textbox', { name: 'Message Shepherd' }).fill('Keep this draft');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'Your draft is kept' }).waitFor();
  if (await page.getByRole('textbox', { name: 'Message Shepherd' }).inputValue() !== 'Keep this draft') throw new Error('Draft lost after failed send');
  await page.unroute('**/messages');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('button', { name: 'Stop response', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Stop response', exact: true }).click();
  await page.getByText('Connected', { exact: true }).waitFor();
  await page.reload();
  await page.getByText('Connected', { exact: true }).waitFor();
  await page.getByText('Where did we leave off?', { exact: true }).waitFor();
  await page.screenshot({ path: '/tmp/shepherd-ui-chat.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Open conversations', exact: true }).click();
  await page.getByRole('button', { name: 'New conversation', exact: true }).click();
  await page.getByRole('button', { name: 'Create conversation', exact: true }).click();
  await page.getByText('Connected', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Message Shepherd' }).fill('A fresh conversation');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('article').getByText('A fresh conversation', { exact: true }).waitFor();
  await page.getByText('Connected', { exact: true }).waitFor();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  if (overflow) throw new Error('Horizontal overflow on narrow layout');
  await page.screenshot({ path: '/tmp/shepherd-ui-mobile.png' });
  await page.getByRole('textbox', { name: 'Message Shepherd' }).fill('Draft across disconnect');
  await page.context().setOffline(true);
  await page.getByText('Reconnecting', { exact: true }).waitFor();
  if (await page.getByRole('textbox', { name: 'Message Shepherd' }).inputValue() !== 'Draft across disconnect') throw new Error('Offline draft lost');
  await page.context().setOffline(false);
  await page.getByText('Connected', { exact: true }).waitFor({ timeout: 15000 });
  await page.evaluate(async () => {
    const conversations = await (await fetch('/api/v1/conversations')).json();
    const selected = JSON.parse(localStorage.getItem('shepherd.selection'));
    if (!conversations.conversations.some(item => item.id === selected.id)) throw new Error('Missing selected handle');
    await fetch(`/api/v1/conversations/${selected.id}`, { method: 'DELETE' });
  });
  await page.getByText('Needs attention', { exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Resume conversation', exact: true }).click();
  await page.getByText('Connected', { exact: true }).waitFor();
  if (await page.getByRole('textbox', { name: 'Message Shepherd' }).inputValue() !== 'Draft across disconnect') throw new Error('Resume draft lost');
  if (errors.length) throw new Error(errors.join('\n'));
  return 'Passed: resume, history, send, streaming, approvals, failed-send draft, interrupt, reload recovery, new conversation, narrow layout, offline reconnect and expired-handle recovery';
}
